### ISSUE TITLE
rake would not work until I changed sqlite version to 1.3.6

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/sinatra-activerecord-setup#16]
Readme says to require sqlite3 gem like so:
`group :development do
        gem 'shotgun'
        gem 'pry'
        gem 'tux'
        gem 'sqlite3'
    end`

Doing so resulted in this error when trying to run rake -T
`rake aborted!
Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).`

Googled and found this solution on StackOverflow:
https://stackoverflow.com/questions/54527277/cant-activate-sqlite3-1-3-6-already-activated-sqlite3-1-4-0

To quote:

> ...I removed the gem that I thought was giving me an error, by 
> gem uninstall sqlite3 -v 1.4.0
>and instead, used in my gem file.  gem 'sqlite3', '~> 1.3.6' 
>Ran the bundle update and it worked like a charm for me.

**Comment by jonnelbenjamin** [comment]
Having the same issue

**Comment by pamccombs** [comment]
I actually just did bundle update and got everything to work.

**Comment by maxwellbenton** [comment]
Hi @joanrig,

Thank you for spotting this and providing feedback. We've updated this lesson's instructions and support files so that students are now instructed to use `gem 'sqlite3', '~> 1.3.6'` and have confirmed that rake is now worked as expected.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
